{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "e3b9f7d0-cc9a-44c3-85b0-dea6e9643856",
   "metadata": {},
   "source": [
    "# cold storage\n",
    "grabs your ao3 bookmarks, downloads them all"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a5633331",
   "metadata": {},
   "source": [
    "### todo\n",
    "1. problem with loading bookmarks not loading everything\n",
    "2. select between epub and pdf download\n",
    "3. try/catch needed for whatever problem is happening in downloading all bookmarks -> it fails on restricted works.\n",
    "4. downloader for loop needs a try/catch statement to catch when a work 404s `utils.InvalidIdError(\"Cannot find work\")`\n",
    "    1. 404s seem to happen mostly on really large works. 400k words kinda works. Glaurung in specific 404ed.\n",
    "5. store metadata locally. -> pickle the bookmarks.works.metadata?\n",
    "6. overwrite existing downloaded file -> https://www.geeksforgeeks.org/python-check-if-a-file-or-directory-exists-2/#exists\n",
    "7. implement multi-threading to cut down on download times. might run into problems with session."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3dba3ddb-c69d-41d1-a657-4d858552ffab",
   "metadata": {},
   "outputs": [],
   "source": [
    "import secret\n",
    "from tools import Downloader"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "8ac71864",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-9:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 94, in req_bookmarks\n",
      "    self._soup_bookmarks = self.request(f\"https://archiveofourown.org/users/{username}/bookmarks\")\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "url: https://archiveofourown.org/users/syrtis_mons\n",
      "bio: \n",
      "works: 2\n",
      "bookmarks: 1239\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "62"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "d = Downloader(secret.username, secret.password,requests_per_min=6, bookmark_pause=5,download_pause=5)\n",
    "d.user._bookmarks_pages"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c6b0eea2",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-11:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Exception in thread Exception in thread Exception in thread Thread-13:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Thread-12:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Thread-17Thread-18Thread-10:\n",
      "Exception in thread :\n",
      "Exception in thread Thread-26:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Thread-14:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread :\n",
      "Exception in thread Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Traceback (most recent call last):\n",
      "Thread-19Exception in thread Exception in thread :\n",
      "Exception in thread Exception in thread Thread-15Exception in thread Thread-16:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Thread-27Thread-36Exception in thread Thread-28:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Thread-20:\n",
      "Traceback (most recent call last):\n",
      "Exception in thread :\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Thread-30:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      ":\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      ":\n",
      "Thread-24:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Traceback (most recent call last):\n",
      "Exception in thread Thread-41:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "        Exception in thread Exception in thread Thread-23:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Thread-43:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Exception in thread self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "Thread-29Exception in thread Thread-48:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Thread-46Exception in thread Exception in thread Thread-50Exception in thread Thread-33:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Thread-38Exception in thread Thread-32Exception in thread :\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Thread-58:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread   File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Thread-31Exception in thread Traceback (most recent call last):\n",
      "Thread-59Exception in thread Thread-60:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "Exception in thread     self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "Exception in thread     Thread-54:\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "Exception in thread Thread-63:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread :\n",
      "Exception in thread Traceback (most recent call last):\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Exception in thread Thread-37self.run()Thread-65:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      ":\n",
      "Exception in thread Exception in thread Exception in thread Exception in thread     self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "Thread-39:\n",
      "Traceback (most recent call last):\n",
      "Thread-57:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Exception in thread     self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Thread-62Exception in thread :\n",
      "Thread-45        Exception in thread Thread-21:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "Thread-68:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    :\n",
      "self._target(*self._args, **self._kwargs)Thread-56self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread     Exception in thread   File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Thread-66  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "Thread-35Thread-22:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Thread-51:\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "Thread-25self.run()  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Thread-53:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Thread-34Thread-64  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "Thread-55:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      ":\n",
      ":\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    :\n",
      "    Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      ":\n",
      "\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Thread-47Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    Exception in thread Thread-61Traceback (most recent call last):\n",
      "      File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "      File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "            self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "\n",
      "\n",
      "Exception in thread Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "Thread-69self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self.run()    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "Exception in thread Thread-44:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      ":\n",
      "    Exception in thread     self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "Thread-70:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "                self.run()    Exception in thread self.run()    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "self.run()                self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "        _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HEREself._target(*self._args, **self._kwargs)    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "self.run()self._target(*self._args, **self._kwargs)self.run()\n",
      "            self.run()        self.run()\n",
      "\n",
      "      File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    Traceback (most recent call last):\n",
      "    \n",
      "self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    \n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "self.run()req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "self.run()\n",
      "\n",
      "      File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "self._target(*self._args, **self._kwargs)  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    \n",
      "\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "self._target(*self._args, **self._kwargs)    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "      File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "      File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    Thread-71self.run()self._target(*self._args, **self._kwargs)\n",
      "self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "\n",
      "    \n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    self.run()    self._target(*self._args, **self._kwargs)    :\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "      File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "      File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    \n",
      "self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "req = self.get(url)      File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "\n",
      "\n",
      "\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "self._target(*self._args, **self._kwargs)    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "                self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "      File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "        \n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    \n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HEREself._target(*self._args, **self._kwargs)req = self.get(url)self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "\n",
      "req = self.get(url)    \n",
      "          File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    self._target(*self._args, **self._kwargs)    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "self._target(*self._args, **self._kwargs)    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "      File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    \n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HEREself._target(*self._args, **self._kwargs)  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "self.run()  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "\n",
      "        _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "        req = self.get(url)\n",
      "\n",
      "req = self.get(url)    self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)        \n",
      "\n",
      "\n",
      "self.run()    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "      File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "self.run()    self._target(*self._args, **self._kwargs)  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "\n",
      "        self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "        \n",
      "self._target(*self._args, **self._kwargs)  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "      File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HEREself._target(*self._args, **self._kwargs)        _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE              File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    req = self.get(url)        self._target(*self._args, **self._kwargs)\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HEREself._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "\n",
      "        _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "AO3.utilsreq = self.get(url)  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "      File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    ._soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE    \n",
      "        self._target(*self._args, **self._kwargs)  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "HTTPError\n",
      "self._target(*self._args, **self._kwargs)  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    :   File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "\n",
      "\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "\n",
      "    \n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "        _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HEREreq = self.get(url)req = self.get(url)self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "self._target(*self._args, **self._kwargs)            We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "        _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.\n",
      "        raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    \n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "self._target(*self._args, **self._kwargs)req = self.get(url)    HTTPError:             req = self.get(url)\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "      File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "            req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requestsraise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPErrorreq = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "        \n",
      "    \n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "                raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "                    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "req = self.get(url)\n",
      "\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE        raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HEREreq = self.get(url)    req = self.get(url)raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requestsreq = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "\n",
      "req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HEREself._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests    \n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    \n",
      "      File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "        raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError:     req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      ": We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "        raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    req = self.get(url)    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "    \n",
      "AO3.utils.HTTPError    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    req = self.get(url)\n",
      "\n",
      ":     raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "            _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    req = self.get(url)  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    req = self.get(url)    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "        req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "\n",
      "                    AO3.utils.HTTPError: req = self.get(url)                req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "We are being rate-limited. Try again in a while or reduce the number of requestsraise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requestsraise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: \n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "\n",
      "req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    \n",
      "AO3.utils.HTTPError    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "Exception in thread Thread-40:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "We are being rate-limited. Try again in a while or reduce the number of requests    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "      File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.Exception in thread Thread-52:\n",
      "Exception in thread     raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    Exception in thread Traceback (most recent call last):\n",
      "Exception in thread : We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "Thread-42:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "\n",
      "AO3.utils.    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")Thread-49    \n",
      "HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests    req = self.get(url)raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "Thread-67:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "      File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "        raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      ":\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "Traceback (most recent call last):\n",
      "    AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "            \n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError:         self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "self.run()    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "        self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "        self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "        _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "        raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "_soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    \n",
      "AO3.utils.HTTPError: req = self.get(url)We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "        _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "    self.run()\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\threading.py\", line 910, in run\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError:     req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "        self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\jonah\\OneDrive\\Documents\\GitHub\\ao3-cold-storage\\tools.py\", line 96, in load_bookmarks_thread\n",
      "req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "        _soup_bookmarks = self.user.request(f\"https://archiveofourown.org/users/{self.user.username}/bookmarks?page={page}\") #TODO FIX ERROR HERE\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 385, in request\n",
      "raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n",
      "    req = self.get(url)\n",
      "  File \"c:\\Users\\jonah\\miniconda3\\envs\\py39_64\\lib\\site-packages\\AO3\\users.py\", line 372, in get\n",
      "    raise utils.HTTPError(\"We are being rate-limited. Try again in a while or reduce the number of requests\")\n",
      "AO3.utils.HTTPError: We are being rate-limited. Try again in a while or reduce the number of requests\n"
     ]
    }
   ],
   "source": [
    "d.load_bookmarks_threaded()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "7324c380",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "num bookmarks loaded: 0\n",
      "est download time: 0.0 minutes\n"
     ]
    }
   ],
   "source": [
    "n = len(d.bookmarks)\n",
    "mult = 30/143\n",
    "print(\"num bookmarks loaded:\", n) # if this returns 0, wait a while and try again\n",
    "print(\"est download time:\", round(n*mult,2), \"minutes\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "02e46c41",
   "metadata": {},
   "outputs": [],
   "source": [
    "d.load_threaded_download_threaded(bookmark_pause=5,download_pause=5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "83291052-aafc-45f2-96f2-dc8c193167d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# config\n",
    "session = AO3.Session(secret.username, secret.password)\n",
    "user = AO3.User(secret.username)\n",
    "user.set_session(session)\n",
    "AO3.utils.limit_requests() # limits the number of requests/minute"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c183d3b9-d508-4cae-a513-a15921ad32b6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# grab all bookmarks\n",
    "AO3.utils.set_rqtw(2)\n",
    "user.reload()\n",
    "bookmarks = user.load_bookmarks_threaded()\n",
    "print(\"url:\", user.url)\n",
    "print(\"bio:\", user.bio)\n",
    "print(\"works:\", user.works)\n",
    "print(\"bookmarks:\", user.bookmarks)\n",
    "print(bookmarks) #prints the first ten works - checks that this cell downloaded right"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "79eac967",
   "metadata": {},
   "source": [
    "- add a print to each line saying how far through the list the prog is\n",
    "- finished print\n",
    "- 404 counter at the end, so you can do success vs failure printout\n",
    "- threading to cut down on download time\n",
    "- decrease 404 time.sleep() to 20sec\n",
    "- 404s occur on restricted works."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5bf0d79a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# downloader\n",
    "AO3.utils.set_rqtw(10)\n",
    "downloader_threaded(bookmarks)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python39_64",
   "language": "python",
   "name": "py39_64"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
